---
title: "R Notebook"
output: html_notebook
---
```{r Load Libraries, message=FALSE, warning=FALSE}
library(shiny)
library(shinythemes)
library(plyr)
library(dplyr)
library(magrittr)
library(wordcloud)
library(ggplot2)
library(plotly)
library(scales)
library(leaflet)
library(tidyr)
library(stringr)
```


```{r Load Data}
#the directory path will vary based on machine
# topicwordsweightresult <- read.table("~/Desktop/ERMining/mallet_output_files/topic_words_weight.txt", header=F, sep="\t")
topicwordsweightresult <- readRDS("data/topic_words_weight.rds")
# tm_values <- read.csv(file = "~/Desktop/ERMining/mallet_output_files/tmodeling_values.csv", header=TRUE)
tm_values <- readRDS("data/tm_values.rds")
topic_keys <- readRDS("data/topickeys.rds")
```


```{r Generate UI Components}
ui <- fluidPage(
  theme= shinytheme("cosmo"),
  
  headerPanel(HTML("Mining the Eleanor Roosevelt <i>My Day</i> Columns")),
  sidebarPanel(
  #sliderInput(inputId = "topic", "Select a Topic", 0, 59, 1, step = 1),
  numericInput(inputId = "topic", "Select a Topic", 1, min = 0, max = 59, step = 1, width = NULL),
      numericInput(inputId = "word_num", "Select a Number of Words to Display", 50, min = 1, max = 50, step = 1, width = NULL),
  sliderInput(inputId = "number_of_topdocs", "Select the Number of Top Documents", 0, 100, 30, step = 1)
  ),
  mainPanel(
    h2(textOutput("TopWordsInTopicNumber")),
    plotOutput("topic_plot") ),
  fluidPage(
    fluidRow(
      column(6, 
             h2("Locations of Top Columns"),
             leafletOutput("doc_map")),
                    
  column(6,
             h2("Yearly proportion of words in topic"),
             textOutput("topicCorpusWeight"),
             plotlyOutput("time_graph")))),
  fluidPage(fluidRow(column(width=12),
                     h2("Top Columns"),
                     dataTableOutput("doc_topics")))
  )


server <- function(input, output) {
  
  
  
  output$topicCorpusWeight <- renderText({ 
    topicweight <- topic_keys %>% filter(V1 == input$topic) 
    topicweight <- topicweight$V2
    paste(topicweight, "% of the corpus in total.")
  })
  output$TopWordsInTopicNumber <- renderText({ 
    paste("Top Words in Topic #",input$topic)
  })
    

  ##output topicwordcloud
  output$topic_plot <- renderPlot({  
    exploretopicwords <- function(topicnum, numwords) {
        require(magrittr)
        require(wordcloud)
        require(dplyr)
        topicwords <- topicwordsweightresult %>% filter(V1 == topicnum) %>% arrange(desc(V3))
        topicwords$V1 <- NULL
        topicwords <- topicwords[1:numwords,]
        wc <- wordcloud(topicwords$V2, topicwords$V3,scale=c(5,1.5), colors=brewer.pal(8, "Dark2"), random.order=FALSE)
        return(wc)  }
       exploretopicwords(input$topic, input$word_num)
    })
    ##output topics over time
    output$time_graph <- renderPlotly({
      exploretopics_byyear <- function(topic) {
        byyear <- ddply(tm_values, .(topicnum, year), summarise, mean_value = mean(value) * 100)
    
        filterbytopicnum <- byyear %>% filter(topicnum == topic)
        tby_plot <- ggplot(filterbytopicnum, aes(year, mean_value)) + geom_bar(stat="identity") + scale_x_continuous(name="Year", breaks=seq(1935, 1962, 2)) + scale_y_continuous(limits=c(0,5))
tby_plot    }
        exploretopics_byyear(input$topic)
    })
    
   output$doc_topics <- renderDataTable({
      doc_topic_assoc <- function(topic) {
  
      #tm_values <- read.csv(file = "mallet_output_files/tmodeling_values.csv", header=TRUE)
      bytopic <- tm_values %>% filter(topicnum == topic) %>% arrange(desc(value)) 
      #a$Numbers <- a$Numbers * b
      ##turn weights into percentages
      bytopic$value <- bytopic$value 
      head(bytopic, n=30)
  }
  doc_topic_assoc(input$topic)
   }, escape=FALSE)
   
   output$doc_map <- renderLeaflet({
      tm_1 <- tm_values %>%
      filter(topicnum == input$topic) %>%
      arrange(desc(value)) 
      tm_1 <- tm_1[1:input$number_of_topdocs,]

      pal <- colorFactor(c("navy", "red", "green"), domain = c("1", "2", "3"))

      leaflet(tm_1) %>%
        addTiles() %>%
        addCircleMarkers(radius = ~(value) *50,
                         color = ~pal(topicnum),
                         stroke = FALSE,
                         label = ~paste("Topic Number = ", input$topic, " | ", "Percent = ", str_sub(value, 1, 4), "%", " | ", Columndate, " | ", "Place Name: ", PlaceName, sep = ""),
                         fillOpacity = 0.3) %>%
        addLegend("topright", pal = pal, values = ~input$topic)
   })
   
}

shinyApp(ui = ui, server = server)
```



